name: Daily run [EastUS2EUAP] - lwa-sample-dotnet-7-francecentral

on: 
  schedule:
    - cron: '20 8 * * *' # every day at 8:20 UTC

env:
  AZURE_WEBAPP_NAME: lwa-sample-dotnet-7-francecentral   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './sampleAppOutput'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.0'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main
        with:
          ref: 'dotnet-7.0'
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS_E2E_SERVICE_PRINCIPAL }}

      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using Azure Credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      
      - name: logout
        run: |
          az logout
